# Regression - Model training and Evaluation

- Dependent variable (y) - predict
- Independent variable (x) - used to predict y

simple linear regression: 
* y = mx+c 
* y = m1x1 + m2x2 + m3x3 + c
* y = m.x.^3 + m2x2^2 + m3x3 + c

Evaluation ways
* MAE - mean abosolute error AVG(y-ypred)
* MSE - Mean squared error (AVG(y-ypred)^2)
* R2 score

#### Finding of R2 score
- R2 = 1- (SSres/Sum of square of total)

In [4]:
import pandas as pd
import numpy as np 

df = pd.read_csv('Book2.csv')
df.head(2)

    x   y
0  15  49
1  23  63

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       15 non-null     int64
 1   y       15 non-null     int64
dtypes: int64(2)
memory usage: 372.0 bytes

In [5]:
df.isna().sum()

x    0
y    0
dtype: int64

In [6]:
print(type(df['x']))
print(type(df['y']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

##### we need x as df and y as series so chaigning them and let's do it

In [9]:
x = df.iloc[:,0:1] # second slicing operator for the type change
y = df.iloc[:,-1] 

print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [12]:
# doing it without test the csv way
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x,y)
y_pred = lr.predict(x)
print(y_pred)

[47.45652174 62.60810811 53.13836663 62.60810811 64.5020564  60.71415981
 60.71415981 55.03231492 55.03231492 49.35047004 64.5020564  39.88072855
 64.5020564  49.35047004 62.60810811]

In [13]:
# difference 
diff = pd.DataFrame({'Actual': y, 'Predict': y_pred})
diff.head()

   Actual    Predict
0      49  47.456522
1      63  62.608108
2      58  53.138367
3      60  62.608108
4      58  64.502056

In [14]:
# errors
print('Coefficent ', lr.coef_)
print('Intercept: ',lr.intercept_)

Coefficent  [1.8939483]
Intercept:  19.04729729729729

In [15]:
# erros 2
from sklearn import metrics
print(f'MAR: {metrics.mean_absolute_error(y,y_pred)}')
print(f'MAS: {metrics.mean_squared_error(y,y_pred)}')
print(f'R2 Score: {metrics.r2_score(y,y_pred)}')

MAR: 3.7412847630238937
MAS: 22.292068155111632
R2 Score: 0.7088287858527739

In [ ]:
# 

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1, random_state=1)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(13, 1)
(2, 1)
(13,)
(2,)

In [20]:
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
print(y_pred)

[62.41322902 54.56827881]

In [26]:
# difference 
diff = pd.DataFrame({'Actual': y_test, 'Predict': y_pred})
diff.head()

   Actual    Predict
3      60  62.413229
7      63  54.568279

In [27]:
# errors
print('Coefficent ', lr.coef_)
print('Intercept: ',lr.intercept_)

Coefficent  [1.96123755]
Intercept:  17.30476529160738

In [29]:
# erros 2
from sklearn import metrics
print(f'MAE: {metrics.mean_absolute_error(y_test,y_pred)}')
print(f'MAS: {metrics.mean_squared_error(y_test,y_pred)}')
print(f'R2 Score: {metrics.r2_score(y_test,y_pred)}')

MAE: 5.422475106685635
MAS: 38.458798301932994
R2 Score: -16.092799245303553