In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

# Regression - Model training and Evaluation

- Dependent variable (y) - predict
- Independent variable (x) - used to predict y

simple linear regression: 
* y = mx+c 
* y = m1x1 + m2x2 + m3x3 + c
* y = m.x.^3 + m2x2^2 + m3x3 + c

Evaluation ways
* MAE - mean abosolute error AVG(y-ypred)
* MSE - Mean squared error (AVG(y-ypred)^2)
* R2 score

#### Finding of R2 score
- R2 = 1- (SSres/Sum of square of total)

In [39]:
df = pd.read_csv("./data.csv")
df

     x   y
0   15  49
1   23  63
2   18  58
3   23  60
4   24  58
5   22  61
6   22  60
7   19  63
8   19  60
9   16  52
10  24  62
11  11  30
12  24  59
13  16  49
14  23  68

In [40]:
x = df.iloc[:,0:1] # second xlicing for type change
y = df.iloc[:,-1]

In [41]:
lr = LinearRegression()
lr.fit(x,y)
y_pred = lr.predict(x)
y_pred

array([47.45652174, 62.60810811, 53.13836663, 62.60810811, 64.5020564 ,
       60.71415981, 60.71415981, 55.03231492, 55.03231492, 49.35047004,
       64.5020564 , 39.88072855, 64.5020564 , 49.35047004, 62.60810811])

In [42]:
# differernce
diff = pd.DataFrame({"Actual": y,"Predication": y_pred})
diff

    Actual  Predication
0       49    47.456522
1       63    62.608108
2       58    53.138367
3       60    62.608108
4       58    64.502056
5       61    60.714160
6       60    60.714160
7       63    55.032315
8       60    55.032315
9       52    49.350470
10      62    64.502056
11      30    39.880729
12      59    64.502056
13      49    49.350470
14      68    62.608108

In [43]:
print("Cofficent", lr.coef_)
print("Intercept",lr.intercept_)

Cofficent [1.8939483]
Intercept 19.04729729729729

In [44]:
print("MAE", metrics.mean_absolute_error(y,y_pred))
print("MSE", metrics.mean_squared_error(y,y_pred))
print("R2 Score", metrics.r2_score(y,y_pred))

MAE 3.7412847630238937
MSE 22.292068155111632
R2 Score 0.7088287858527739

In [46]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1, random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(13, 1)
(2, 1)
(13,)
(2,)

In [47]:
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
y_pred

array([62.41322902, 54.56827881])

In [49]:
diff = pd.DataFrame({"Actual": y_test,"Predication": y_pred})
diff

   Actual  Predication
3      60    62.413229
7      63    54.568279

In [50]:
print("Cofficent", lr.coef_)
print("Intercept",lr.intercept_)

Cofficent [1.96123755]
Intercept 17.30476529160738

In [52]:
print("MAE", metrics.mean_absolute_error(y_test,y_pred))
print("MSE", metrics.mean_squared_error(y_test,y_pred))
print("R2 Score", metrics.r2_score(y_test,y_pred))

MAE 5.422475106685635
MSE 38.458798301932994
R2 Score -16.092799245303553

In [64]:
m = {}
for  i in range(43):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1, random_state=i)
    lr = LinearRegression()
    lr.fit(x_train,y_train)
    y_pred = lr.predict(x_test)
    m[i]= metrics.mean_absolute_error(y_test,y_pred)
 
minimum = min(m.values())
k = [i for i,j in m.items() if j ==minimum]
print(k,minimum)

[5] 0.4198834668608953